refix task 0 and 1

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -4,11 +4,17 @@
 # Distribute requests using a roundrobin algorithm
 # Make sure that HAProxy can be managed via an init script
 
-# Install and configure HAproxy on my lb-01 server.
+# Install and configure HAProxy on lb-01 server.
 sudo apt-get -y update
 sudo apt-get -y install haproxy
 
-# edit config file
+# Check if haproxy installation was successful
+if [ $? -ne 0 ]; then
+    echo "Error: HAProxy installation failed."
+    exit 1
+fi
+
+# Edit config file
 server_config=\
 "
 frontend  IA-LINK_frontend
@@ -17,16 +23,9 @@ frontend  IA-LINK_frontend
         default_backend IA-LINK_backend
 backend IA-LINK_backend
         balance roundrobin
-        server 470338-web-01 54.236.45.50:80 check
-        server 470338-web-02 107.23.104.2:80 check
+        server 471746-web-01 54.236.45.50:80 check
+        server 471746-web-02 107.23.104.2:80 check
 "
 echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
 
-# enable haproxy to be started by init script
-echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
-
-# Testing the HAproxy configuration file
-sudo haproxy -c -f /etc/haproxy/haproxy.cfg
-
-# Restart the Nginx service
-sudo service haproxy restart
+# Enable haproxy to be started by init script
